backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: public/uploads
public_folder: /uploads

collections:
    - name: pages
    label: Pages du site
    files:
            - file: content/accueil.json
        label: Page Accueil
        name: accueil
        fields:
                    - {label: Titre, name: titre, widget: string}
                    - {label: Sous-titre, name: sous_titre, widget: text}
                    - {label: Texte bienvenue, name: bienvenue, widget: markdown}
